import React from "react";
import { Users, CheckCircle2 } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Marketing & Salesman Training | Knowledge Hub",
  description: "Modern sales psychology meets digital tools. Explore how to empower human connection in a digital-first world through professional training.",
};

export default function MarketingSalesmanTrainingPage() {
  return (
    <>
        <article className="w-full">
          
          {/* Header Section */}
          <header className="mb-16 text-center">
            <div className="inline-flex items-center justify-center p-4 bg-amber-500/10 rounded-full mb-8 ring-1 ring-amber-500/20">
              <Users className="w-8 h-8 text-amber-400" />
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-white via-slate-200 to-slate-400 leading-tight">
              Marketing & Salesman Training
            </h1>
            <p className="text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed">
              Equipping teams with modern sales psychology, advanced digital tools, and the interpersonal skills needed to close deals in the 21st century.
            </p>
          </header>

          {/* Featured Image/Graphic Placeholder */}
          <div className="w-full h-[400px] rounded-3xl bg-slate-900 border border-slate-800 mb-16 relative overflow-hidden flex items-center justify-center">
             <div className="absolute inset-0 bg-gradient-to-br from-amber-500/10 to-orange-500/10" />
             <div className="absolute inset-0 bg-[url('/grid-pattern.svg')] opacity-20" />
             <p className="text-slate-500 font-medium tracking-widest uppercase">Professional Development Insights</p>
          </div>

          {/* Content Body */}
          <div className="prose prose-invert prose-lg max-w-none prose-headings:text-slate-100 prose-a:text-amber-400 hover:prose-a:text-amber-300">
            
            <h2>The Evolution of the Sales Professional</h2>
            <p>
              The era of the "hard sell" is over. Today's consumers are highly educated; by the time they speak to a sales representative, they have often already researched the product, read reviews, and compared competitors online. This fundamental shift means that modern salespeople can no longer act merely as walking brochures. They must act as trusted advisors and consultants.
            </p>
            <p>
              Marketing and sales training in the digital age is about bridging the gap between automated digital funnels and the vital human touch that closes complex deals. It requires a deep understanding of human psychology combined with a mastery of modern CRM (Customer Relationship Management) tools and digital communication platforms.
            </p>

            <h2>Psychology Meets Technology</h2>
            <p>
              A common mistake organizations make is heavily investing in digital marketing software while neglecting the human team operating it. A lead generated by a brilliant Facebook ad is worthless if the salesperson who receives it lacks the empathy and negotiation skills to bring it across the finish line.
            </p>
            <p>
              Modern training focuses heavily on active listening, objection handling, and relationship building. However, it also requires training on how to use data. A modern salesman needs to know how to read a prospect's digital footprint, track email open rates, and leverage LinkedIn for social selling. It is this hybrid skill set—part psychologist, part technologist—that defines the top performers today.
            </p>

            <div className="my-12 p-8 rounded-2xl bg-slate-900 border border-slate-800">
              <h3 className="text-xl font-semibold mb-4 text-white mt-0">Core Modules of Modern Sales Training</h3>
              <ul className="space-y-4 list-none pl-0">
                <li className="flex items-start">
                  <CheckCircle2 className="w-6 h-6 text-amber-400 mr-3 shrink-0 mt-0.5" />
                  <span><strong>Consultative Selling:</strong> Shifting the mindset from "pushing a product" to "solving a problem." Asking the right questions to uncover deep-seated pain points.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle2 className="w-6 h-6 text-amber-400 mr-3 shrink-0 mt-0.5" />
                  <span><strong>Digital Tool Mastery:</strong> Training on CRM software, pipeline management, automated follow-up sequencing, and data analytics.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle2 className="w-6 h-6 text-amber-400 mr-3 shrink-0 mt-0.5" />
                  <span><strong>Resilience & Mindset:</strong> Developing the emotional intelligence to handle rejection and maintain high performance in high-pressure environments.</span>
                </li>
              </ul>
            </div>

            <h2>How We Approach Training</h2>
            <p>
              We don't believe in generic, off-the-shelf training seminars. When we work with a sales team, we begin by auditing their current processes. We listen to live sales calls, analyze their digital pipelines, and identify the specific bottlenecks where leads are falling out.
            </p>
            <p>
              Our training programs are highly interactive, utilizing role-play scenarios based on real-world objections the team actually faces. We emphasize actionable techniques over theoretical models. We also focus heavily on aligning the marketing department with the sales department, ensuring that the messaging is consistent from the first ad impression to the final contract signature.
            </p>

            <h2>Why Organizations Invest in Training</h2>
            <p>
              Turnover in sales departments is notoriously high, and the cost of replacing an underperforming salesperson is astronomical. Organizations understand that investing in their human capital provides the highest ROI of any marketing initiative.
            </p>
            <p>
              By bringing in outside expertise to train their teams, companies break internal echo chambers. They expose their staff to the latest industry standards and advanced techniques. Ultimately, organizations invest in training because a well-trained, confident, and technologically adept sales force is the most powerful engine for scalable revenue growth.
            </p>

          </div>
          
          {/* Footer CTA */}
          <div className="mt-16 pt-16 border-t border-slate-800 text-center">
            <h3 className="text-2xl font-bold text-white mb-4">Empower your sales team today.</h3>
            <p className="text-slate-400 mb-8 max-w-2xl mx-auto">
              Contact us to discuss custom training programs designed to increase your closing rates and build lasting client relationships.
            </p>
            <Link 
              href="/contact"
              className="inline-flex justify-center px-8 py-3.5 text-sm font-semibold text-white bg-amber-600 hover:bg-amber-500 rounded-full transition-all hover:scale-105 shadow-[0_0_20px_rgba(245,158,11,0.3)]"
            >
              Request a Training Audit
            </Link>
          </div>

        </article>
    </>
  );
}
